#!/usr/bin/env node
/**
 * Inline `files/` into a module, so the generator can run where there is no filesystem.
 *
 * The CLI reads the directory. A browser cannot, and neither can a Worker — so trokky.build
 * gets the same tree as source: text inline, binary base64 (a generated module has to be valid
 * JavaScript, and 1.5MB of JPEG is not).
 *
 * Emitted as two modules on purpose. The text is a few tens of kilobytes and every composition
 * needs it; the binary is the magazine's photographs and PDFs, which only matter if someone
 * picks that content model — so a page can import it lazily instead of shipping it to everyone.
 */

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const filesRoot = join(root, 'files')
const outDir = join(root, 'src', 'generated')

const isBinary = path => /\.(jpg|jpeg|png|gif|webp|pdf|ico|woff2?)$/i.test(path)

const text = {}
const binary = {}

const walk = dir => {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      walk(full)
      continue
    }
    const key = relative(filesRoot, full).split(sep).join('/')
    if (isBinary(key)) binary[key] = readFileSync(full).toString('base64')
    else text[key] = readFileSync(full, 'utf8')
  }
}
walk(filesRoot)

mkdirSync(outDir, { recursive: true })

const banner = name => `/**
 * GENERATED by scripts/inline-files.mjs — do not edit.
 *
 * ${name}
 */\n\n`

writeFileSync(
  join(outDir, 'files-text.ts'),
  banner('Every text file under files/, so the generator can run without a filesystem.') +
    `export const text: Record<string, string> = ${JSON.stringify(text, null, 0)}\n`,
)

writeFileSync(
  join(outDir, 'files-binary.ts'),
  banner(
    'The magazine\'s images and PDFs, base64. Imported lazily: only a composition that chooses\n * that content model needs them, and they are most of the payload.',
  ) + `export const binary: Record<string, string> = ${JSON.stringify(binary, null, 0)}\n`,
)

const kb = value => `${Math.round(value / 1024)}KB`
console.log(
  `inlined ${Object.keys(text).length} text files (${kb(JSON.stringify(text).length)}) ` +
    `and ${Object.keys(binary).length} binary (${kb(JSON.stringify(binary).length)})`,
)
